### ISSUE TITLE
导致 moblink的restoreScene监听失效

### ISSUE THREAD

**Issue by 228100868** [Wayaer/fl_shared_link#4]
请问有没有遇到过这个问题，同时接入fl_shared_link 和 moblink，会导致moblink的restoreScene在冷启动时监听不到事件。网上查到 有人说增加对AppDelegate中方法的拦截 [registrar addApplicationDelegate:instance]时有些注意事项(https://blog.csdn.net/gaoyp/article/details/114023219 ),但是我尝试修改失败。请作者有空时看下这个问题，感谢

**Comment by Wayaer** [comment]
依赖换成 github 地址 main 分支， 看看能不能行， 可以的话 我就发个新版本
